# Generated by Django 2.2.10 on 2021-12-15 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=50, verbose_name='Компонент')),
                ('sku', models.CharField(max_length=50, verbose_name='Артикул')),
                ('vendor', models.CharField(max_length=50, verbose_name='Vendor')),
                ('vendor_pn', models.CharField(max_length=50, verbose_name='Vendop P/N')),
                ('term_delivery', models.CharField(max_length=50, verbose_name='Условие доставки')),
            ],
        ),
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_name', models.CharField(max_length=50, verbose_name='Тип партии')),
                ('value', models.IntegerField(verbose_name='Значение')),
            ],
        ),
        migrations.CreateModel(
            name='PriceComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_dict', to='components.ComponentDict', verbose_name='Компонент')),
                ('lot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='components.Lots', verbose_name='Партия')),
            ],
        ),
    ]
